# Generated by Django 4.1.2 on 2022-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_transaction_user_id_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='coin_id',
            field=models.CharField(max_length=100),
        ),
    ]
