# Generated by Django 4.1.2 on 2022-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_coin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
